p = PLAFProgram()

@GROUP(p, s for s in propertynames(X) if contains(string(s), "Blind_Make"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Blind_Model"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat1_"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat2"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat3"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat4"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat5"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat6"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat7"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat8"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat9"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat10"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat11"))
@GROUP(p, s for s in propertynames(X) if contains(string(s), "Cat12"))
