p = initPLAF()

@PLAF(p, :cf.ExternalRiskEstimate .>= :x.ExternalRiskEstimate)
@PLAF(p, :cf.MSinceOldestTradeOpen .>= :x.MSinceOldestTradeOpen)
@PLAF(p, :cf.MSinceMostRecentTradeOpen .>= :x.MSinceMostRecentTradeOpen)
@PLAF(p, :cf.AverageMInFile .>= :x.AverageMInFile)
@PLAF(p, :cf.PercentTradesNeverDelq .>= :x.PercentTradesNeverDelq)
@PLAF(p, :cf.MSinceMostRecentDelq .>= :x.MSinceMostRecentDelq)
@PLAF(p, :cf.MaxDelq2PublicRecLast12M .>= :x.MaxDelq2PublicRecLast12M)
@PLAF(p, :cf.MaxDelqEver .>= :x.MaxDelqEver)
@PLAF(p, :cf.NumTotalTrades .>= :x.NumTotalTrades)
@PLAF(p, :cf.NumTradesOpeninLast12M .>= :x.NumTradesOpeninLast12M)
@PLAF(p, :cf.MSinceMostRecentInqexcl7days .>= :x.MSinceMostRecentInqexcl7days)
@PLAF(p, :cf.NumTradesOpeninLast12M .>= :x.NumTradesOpeninLast12M)
@PLAF(p, :cf.NumTradesOpeninLast12M .>= :x.NumTradesOpeninLast12M)
@PLAF(p, :cf.NumTradesOpeninLast12M .>= :x.NumTradesOpeninLast12M)
@PLAF(p, :cf.NumTradesOpeninLast12M .>= :x.NumTradesOpeninLast12M)


@PLAF(p, :cf.NumTrades60Ever2DerogPubRec .<= :x.NumTrades60Ever2DerogPubRec)
@PLAF(p, :cf.PercentInstallTrades .<= :x.PercentInstallTrades)
@PLAF(p, :cf.NumInqLast6M .<= :x.NumInqLast6M)
@PLAF(p, :cf.NumInqLast6Mexcl7days .<= :x.NumInqLast6Mexcl7days)
@PLAF(p, :cf.NetFractionRevolvingBurden .<= :x.NetFractionRevolvingBurden)
@PLAF(p, :cf.NetFractionInstallBurden .<= :x.NetFractionInstallBurden)
@PLAF(p, :cf.NumBank2NatlTradesWHighUtilization .<= :x.NumBank2NatlTradesWHighUtilization)
@PLAF(p, :cf.PercentTradesWBalance .<= :x.PercentTradesWBalance)
